-- ATLAS Person DB integrity migration
-- Run once in Supabase SQL Editor.

begin;

create or replace function public.atlas_normalize_text(value text)
returns text
language sql
immutable
parallel safe
as $$
  select lower(regexp_replace(trim(coalesce(value, '')), '\s+', ' ', 'g'));
$$;

-- 1) Remove exact duplicate activity rows, keeping the lowest id.
delete from public.person_politics a
using public.person_politics b
where a.id > b.id
  and public.atlas_normalize_text(a.person_name) = public.atlas_normalize_text(b.person_name)
  and public.atlas_normalize_text(a.politic_name) = public.atlas_normalize_text(b.politic_name)
  and a.activity_start = b.activity_start
  and a.activity_end = b.activity_end;

-- 2) Prevent exact activity duplicates at database level.
create unique index if not exists person_politics_unique_activity_norm
on public.person_politics (
  public.atlas_normalize_text(person_name),
  public.atlas_normalize_text(politic_name),
  activity_start,
  activity_end
);

-- 3) Canonical person registry. One historical identity has one canonical name.
create table if not exists public.person_registry (
  id bigint generated by default as identity primary key,
  canonical_name text not null,
  display_name_ko text,
  historicity text not null default 'historical',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists person_registry_unique_canonical_norm
on public.person_registry (public.atlas_normalize_text(canonical_name));

insert into public.person_registry (canonical_name)
select distinct p.person_name
from public.person_politics p
where nullif(trim(p.person_name), '') is not null
on conflict do nothing;

-- 4) Alias registry. Korean names, alternate spellings and titles resolve to one person.
create table if not exists public.person_aliases (
  id bigint generated by default as identity primary key,
  person_id bigint not null references public.person_registry(id) on delete cascade,
  alias text not null,
  alias_type text not null default 'alternate',
  created_at timestamptz not null default now()
);

create unique index if not exists person_aliases_unique_alias_norm
on public.person_aliases (public.atlas_normalize_text(alias));

-- Canonical names also act as aliases.
insert into public.person_aliases (person_id, alias, alias_type)
select r.id, r.canonical_name, 'canonical'
from public.person_registry r
on conflict do nothing;

-- 5) Duplicate and suspicious-variant audit views.
create or replace view public.person_politics_exact_duplicates as
select
  public.atlas_normalize_text(person_name) as person_key,
  public.atlas_normalize_text(politic_name) as politic_key,
  activity_start,
  activity_end,
  count(*) as duplicate_count,
  array_agg(id order by id) as row_ids,
  array_agg(distinct person_name) as person_names,
  array_agg(distinct politic_name) as politic_names
from public.person_politics
group by 1,2,3,4
having count(*) > 1;

create or replace view public.person_name_variants as
select
  public.atlas_normalize_text(person_name) as normalized_name,
  count(distinct person_name) as variant_count,
  array_agg(distinct person_name order by person_name) as variants,
  count(*) as activity_rows
from public.person_politics
group by 1
having count(distinct person_name) > 1;

create or replace view public.person_period_overlaps as
select
  a.id as row_a_id,
  b.id as row_b_id,
  a.person_name,
  a.politic_name as politic_a,
  b.politic_name as politic_b,
  a.activity_start as start_a,
  a.activity_end as end_a,
  b.activity_start as start_b,
  b.activity_end as end_b
from public.person_politics a
join public.person_politics b on a.id < b.id
 and public.atlas_normalize_text(a.person_name) = public.atlas_normalize_text(b.person_name)
 and greatest(a.activity_start, b.activity_start) <= least(a.activity_end, b.activity_end)
where not (
  public.atlas_normalize_text(a.politic_name) = public.atlas_normalize_text(b.politic_name)
  and a.activity_start = b.activity_start
  and a.activity_end = b.activity_end
);

-- 6) Name resolution RPC used by the admin UI before insert/update.
create or replace function public.resolve_person_identity(input_name text)
returns table(person_id bigint, canonical_name text, matched_alias text)
language sql
stable
security definer
set search_path = public
as $$
  select r.id, r.canonical_name, a.alias
  from public.person_aliases a
  join public.person_registry r on r.id = a.person_id
  where public.atlas_normalize_text(a.alias) = public.atlas_normalize_text(input_name)
  limit 1;
$$;

grant select on public.person_registry, public.person_aliases to anon, authenticated;
grant select on public.person_politics_exact_duplicates, public.person_name_variants, public.person_period_overlaps to anon, authenticated;
grant execute on function public.resolve_person_identity(text) to anon, authenticated;

commit;
