import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
const readJson=(p)=>JSON.parse(fs.readFileSync(p,'utf8'));
const sources=readJson('stage2/authoring/p7-himiko-chronology-sources.v1.json');
const plan=readJson('stage2/execution/p7-himiko-chronology-execution.v1.json');
function uuidBytes(uuid){return Buffer.from(String(uuid).replaceAll('-',''),'hex');}
function uuid5(namespace,name){const h=crypto.createHash('sha1').update(Buffer.concat([uuidBytes(namespace),Buffer.from(name,'utf8')])).digest();const b=Buffer.from(h.subarray(0,16));b[6]=(b[6]&0x0f)|0x50;b[8]=(b[8]&0x3f)|0x80;const x=b.toString('hex');return `${x.slice(0,8)}-${x.slice(8,12)}-${x.slice(12,16)}-${x.slice(16,20)}-${x.slice(20)}`;}
test('Himiko reviewed academic Sources are deterministic literal identities',()=>{assert.equal(sources.sources.length,2);for(const e of sources.sources){assert.equal(e.row.id,uuid5(sources.uuid_allocation.repository_namespace,`p7:source:${e.row.source_key}`));assert.equal(e.row.sha256,null);assert.equal(e.row.bytes,null);}assert.equal(sources.sources[0].row.id,'63fa169b-cf86-5396-874e-8d0065d9a9a0');assert.equal(sources.sources[1].row.id,'41f02eb1-f20c-5366-8f1a-170effabafce');assert.equal(sources.rules.territory_location_dispute_must_not_be_resolved_by_chronology_authoring,true);});
test('Himiko chronology expresses uncertainty instead of fabricating exact dates or territory',()=>{const op=plan.operations[0];assert.equal(op.type,'rewrite_activity');assert.equal(op.activity_id,'6c92fb98-4066-5e7b-a26f-2a83e8e1a1a6');assert.equal(op.baseline_before.activity_start,180);assert.equal(op.baseline_before.activity_end,248);assert.equal(op.after.activity_start,183);assert.equal(op.after.activity_end,248);assert.equal(op.after.activity_id,op.activity_id);assert.equal(op.after.person_id,op.baseline_before.person_id);assert.equal(op.after.polity_id,op.baseline_before.polity_id);assert.equal(op.after.role_id,op.baseline_before.role_id);assert.equal(op.after.period_basis_id,op.baseline_before.period_basis_id);assert.equal(op.after.relation_type_id,'7ca4de8f-01d4-542c-acc1-a06848c6742c');assert.deepEqual(op.after.activity_start_detail,{year:183,month:null,day:null,granularity:'year',certainty:'approximate',calendar:'unspecified_historical'});assert.deepEqual(op.after.activity_end_detail,{year:248,month:null,day:null,granularity:'year',certainty:'approximate',calendar:'unspecified_historical'});assert.equal(op.after.notes_policy,'PRESERVE_EXACT_LIVE_NOTES');assert.equal(op.after.add_source_links.length,2);assert.equal(plan.execution_rules.territory_and_location_dispute_remains_authoring_only_for_p14,true);assert.equal(plan.result.territory_dispute_resolved,false);assert.equal(plan.execution_rules.production_mutation_authorized,false);});
