import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
const readJson=(p)=>JSON.parse(fs.readFileSync(p,'utf8'));
const sources=readJson('stage2/authoring/p7-cunobeline-chronology-sources.v1.json');
const plan=readJson('stage2/execution/p7-cunobeline-chronology-execution.v1.json');
function uuidBytes(uuid){return Buffer.from(String(uuid).replaceAll('-',''),'hex');}
function uuid5(namespace,name){const h=crypto.createHash('sha1').update(Buffer.concat([uuidBytes(namespace),Buffer.from(name,'utf8')])).digest();const b=Buffer.from(h.subarray(0,16));b[6]=(b[6]&0x0f)|0x50;b[8]=(b[8]&0x3f)|0x80;const x=b.toString('hex');return `${x.slice(0,8)}-${x.slice(8,12)}-${x.slice(12,16)}-${x.slice(16,20)}-${x.slice(20)}`;}
test('Cunobeline reviewed British Museum Source is deterministic',()=>{const e=sources.sources[0];assert.equal(sources.sources.length,1);assert.equal(e.candidate_key,'bibliographic:british-museum:cunobelin');assert.equal(e.row.id,uuid5(sources.uuid_allocation.repository_namespace,`p7:source:${e.row.source_key}`));assert.equal(e.row.id,'bacced69-c4de-5990-8496-4e964967eb2b');assert.equal(e.row.sha256,null);assert.equal(e.row.bytes,null);assert.equal(sources.rules.production_mutation_authorized,false);});
test('Cunobeline correction normalizes 9-40 to approximate 10-40 without identity drift',()=>{const op=plan.operations[0];assert.equal(plan.operations.length,1);assert.equal(plan.execution_rules.production_executable,false);assert.equal(plan.execution_rules.production_mutation_authorized,false);assert.equal(op.activity_id,'ab0b9158-9395-5f02-b560-c12c5671b879');assert.equal(op.baseline_before.activity_start,9);assert.equal(op.baseline_before.activity_end,40);assert.equal(op.after.activity_start,10);assert.equal(op.after.activity_end,40);assert.equal(op.after.activity_id,op.activity_id);assert.equal(op.after.person_id,op.baseline_before.person_id);assert.equal(op.after.polity_id,op.baseline_before.polity_id);assert.equal(op.after.role_id,op.baseline_before.role_id);assert.equal(op.after.period_basis_id,op.baseline_before.period_basis_id);assert.equal(op.after.relation_type_id,'7ca4de8f-01d4-542c-acc1-a06848c6742c');assert.equal(op.after.activity_start_detail.certainty,'approximate');assert.equal(op.after.activity_end_detail.certainty,'approximate');assert.equal(op.after.activity_start_detail.month,null);assert.equal(op.after.activity_end_detail.day,null);assert.equal(op.after.notes_policy,'REPLACE_WITH_REVIEWED_NOTES');assert.match(op.after.reviewed_notes,/approximately AD 10–40/);assert.equal(op.after.add_source_links[0].source_id,sources.sources[0].row.id);});
