import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
const readJson=(p)=>JSON.parse(fs.readFileSync(p,'utf8'));
const sources=readJson('stage2/authoring/p7-yoshida-term-sources.v1.json');
const plan=readJson('stage2/execution/p7-yoshida-term-split-execution.v1.json');
function uuidBytes(uuid){return Buffer.from(String(uuid).replaceAll('-',''),'hex');}
function uuid5(namespace,name){const h=crypto.createHash('sha1').update(Buffer.concat([uuidBytes(namespace),Buffer.from(name,'utf8')])).digest();const b=Buffer.from(h.subarray(0,16));b[6]=(b[6]&0x0f)|0x50;b[8]=(b[8]&0x3f)|0x80;const x=b.toString('hex');return `${x.slice(0,8)}-${x.slice(8,12)}-${x.slice(12,16)}-${x.slice(16,20)}-${x.slice(20)}`;}
test('Yoshida PMO Source and new Activity UUID are deterministic literal identities',()=>{assert.equal(sources.sources.length,1);const s=sources.sources[0];assert.equal(s.row.id,uuid5(sources.uuid_allocation.repository_namespace,`p7:source:${s.row.source_key}`));assert.equal(s.row.id,'b223cd66-218d-59a7-81f2-6ec35fe201e3');assert.equal(plan.new_activity_uuid_allocations.length,1);const alloc=plan.new_activity_uuid_allocations[0];assert.equal(alloc.activity_uuid,uuid5(plan.uuid_allocation.repository_namespace,`p7:activity:0c084a88-58be-52e8-81bb-b73bf0a11bb1:${alloc.fragment_id}`));assert.equal(alloc.activity_uuid,'23a9fd92-eaad-5a7a-bc09-fd47137e536c');});
test('Yoshida split preserves the official 1947-1948 non-office gap with exact day boundaries',()=>{const op=plan.operations[0];assert.equal(op.type,'split_activity');assert.equal(op.activity_id,'0c084a88-58be-52e8-81bb-b73bf0a11bb1');assert.equal(op.fragments.length,2);const [first,second]=op.fragments;assert.equal(first.survivor,true);assert.equal(first.activity_id,op.activity_id);assert.equal(first.activity_start,1946);assert.equal(first.activity_end,1947);assert.deepEqual(first.activity_start_detail,{year:1946,month:5,day:22,granularity:'day',certainty:'exact',calendar:'gregorian'});assert.deepEqual(first.activity_end_detail,{year:1947,month:5,day:24,granularity:'day',certainty:'exact',calendar:'gregorian'});assert.equal(second.survivor,false);assert.equal(second.activity_id,'23a9fd92-eaad-5a7a-bc09-fd47137e536c');assert.equal(second.legacy_source_key,null);assert.equal(second.source_copy_policy,'COPY_EXISTING');assert.deepEqual(second.activity_start_detail,{year:1948,month:10,day:15,granularity:'day',certainty:'exact',calendar:'gregorian'});assert.deepEqual(second.activity_end_detail,{year:1954,month:12,day:10,granularity:'day',certainty:'exact',calendar:'gregorian'});for(const fragment of op.fragments){assert.equal(fragment.person_id,op.baseline_before.person_id);assert.equal(fragment.polity_id,op.baseline_before.polity_id);assert.equal(fragment.role_id,op.baseline_before.role_id);assert.equal(fragment.period_basis_id,op.baseline_before.period_basis_id);assert.equal(fragment.relation_type_id,'67a57b37-1853-5f2a-b7ab-e6b2d32b56b6');assert.equal(fragment.notes_policy,'REPLACE_WITH_REVIEWED_NOTES');assert.equal(fragment.add_source_links[0].source_id,sources.sources[0].row.id);}assert.match(op.gap_overlap_policy,/1947_05_25_THROUGH_1948_10_14/);assert.equal(plan.execution_rules.production_mutation_authorized,false);});
