import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';

const require=createRequire(import.meta.url);
const {requiredSnapshotActivityIds,mergeSourceLinks,synthesizeCorrectionV2Manifest}=require('../server/atlas-correction-v2-manifest-synthesizer.js');
const {snapshotDigest}=require('../server/atlas-correction-v2-snapshot-service.js');
const TARGET='11111111-1111-4111-8111-111111111111',SURVIVOR='22222222-2222-4222-8222-222222222222',PERSON='33333333-3333-4333-8333-333333333333',POLITY='44444444-4444-4444-8444-444444444444',ROLE='55555555-5555-4555-8555-555555555555',PERIOD='66666666-6666-4666-8666-666666666666',SOURCE='77777777-7777-4777-8777-777777777777';
function activity(id,start,end){return{id,person_id:PERSON,polity_id:POLITY,relation_type_id:null,role_id:ROLE,period_basis_id:PERIOD,activity_start:start,activity_start_month:null,activity_start_day:null,activity_start_granularity:null,activity_start_certainty:null,activity_start_calendar:null,activity_end:end,activity_end_month:null,activity_end_day:null,activity_end_granularity:null,activity_end_certainty:null,activity_end_calendar:null,confidence:'reviewed',chronology_status:'reviewed',legacy_source_key:`legacy:${id}`,notes:'n',source_locator:{kind:'legacy'},content_hash:'h'};}
function retirePlan(){return{schema:'atlas-stage2-correction-v2-execution-plan/v1',batch_id:'fixture-retire',baseline:{},execution_rules:{production_executable:false,production_mutation_authorized:false},operations:[{case_id:'retire',type:'retire_activity',activity_id:TARGET,baseline_before:{person_id:PERSON,polity_id:POLITY,role_id:ROLE,period_basis_id:PERIOD,activity_start:1,activity_end:2,confidence:'reviewed',chronology_status:'reviewed',legacy_source_key:`legacy:${TARGET}`,source_count:1},replacement_activity_ids:[SURVIVOR],silent_source_drop_forbidden:true}],companion_assertions:[]};}
function snapshot(){const core={schema:'atlas-correction-v2-target-snapshot/v1',activity_ids:[TARGET,SURVIVOR].sort(),activities:[activity(TARGET,1,2),activity(SURVIVOR,1,3)].sort((a,b)=>a.id.localeCompare(b.id)),normalized_activity_source_links:[{person_politics_id:TARGET,source_id:SOURCE,source_locator_key:'target locator'}],chronology_claims:[],relationship_descriptions:[]};return{...core,snapshot_digest:snapshotDigest(core)};}
test('retire snapshot includes reviewed survivor',()=>assert.deepEqual(requiredSnapshotActivityIds(retirePlan()),[TARGET,SURVIVOR].sort()));
test('retire synthesis transfers source evidence before delete',()=>{const op=synthesizeCorrectionV2Manifest(retirePlan(),snapshot()).operations[0];assert.equal(op.source_transfer_required,true);assert.deepEqual(op.replacement_activities[0].exact_after.normalized_source_links,[{person_politics_id:SURVIVOR,source_id:SOURCE,source_locator_key:'target locator'}]);});
test('source merge fails closed on locator conflict',()=>{assert.deepEqual(mergeSourceLinks([{person_politics_id:SURVIVOR,source_id:SOURCE,source_locator_key:'same'}],[{person_politics_id:TARGET,source_id:SOURCE,source_locator_key:'same'}],SURVIVOR,'fixture'),[{person_politics_id:SURVIVOR,source_id:SOURCE,source_locator_key:'same'}]);assert.throws(()=>mergeSourceLinks([{person_politics_id:SURVIVOR,source_id:SOURCE,source_locator_key:'old'}],[{person_politics_id:TARGET,source_id:SOURCE,source_locator_key:'new'}],SURVIVOR,'fixture'),/CORRECTION_V2_RETIRE_SOURCE_LOCATOR_CONFLICT/);});
