import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);
const p14=require('../server/atlas-p14-territory-geometry-contract.js');
const territory={polity_id:'polity',geometry_id:'g1',control_type:'de_facto_control',boundary_certainty:'approximate',evidence_confidence:'probable',valid_start:1584,valid_end:1590,source_refs:['source:locator']};
const geometry={geometry_id:'g1',geometry_kind:'polygon',geometry_ref:'repo://geometry/g1',provenance:{source_ref:'source:locator',invented:false}};
test('Unit 15 seals Person Activity Polity TerritoryRecord Geometry chain',()=>{assert.deepEqual(p14.CONTRACT.chain,['Person','Activity','Polity','TerritoryRecord','Geometry']);assert.equal(p14.assertTerritoryGeometryLink(territory,geometry),true);});
test('Unit 15 TerritoryRecord preserves political semantics and provenance',()=>{for(const k of ['control_type','boundary_certainty','evidence_confidence','valid_start','valid_end','source_refs'])assert.ok(p14.CONTRACT.territory_record.required.includes(k));assert.throws(()=>p14.assertTerritoryRecord({...territory,valid_start:0}),/YEAR_INVALID/);assert.throws(()=>p14.assertTerritoryRecord({...territory,source_refs:[]}),/SOURCE_REQUIRED/);});
test('Unit 15 forbids Person or Activity owned territory and display authority fabrication',()=>{assert.throws(()=>p14.assertTerritoryRecord({...territory,person_id:'person'}),/PERSON_ACTIVITY_OWNED/);assert.throws(()=>p14.assertTerritoryRecord({...territory,activity_id:'activity'}),/PERSON_ACTIVITY_OWNED/);assert.throws(()=>p14.assertTerritoryRecord({...territory,region_code:'east_asia'}),/DISPLAY_FIELD/);});
test('Unit 15 Geometry is reusable shape, not political authority',()=>{assert.throws(()=>p14.assertGeometry({...geometry,polity_id:'p'}),/HISTORICAL_AUTHORITY/);assert.throws(()=>p14.assertGeometry({...geometry,control_type:'sovereign_control'}),/HISTORICAL_AUTHORITY/);assert.throws(()=>p14.assertGeometry({...geometry,provenance:{invented:true}}),/INVENTED_GEOMETRY/);});
test('Unit 15 requires exact TerritoryRecord Geometry reference',()=>{assert.throws(()=>p14.assertTerritoryGeometryLink({...territory,geometry_id:'g2'},geometry),/LINK_MISMATCH/);assert.equal(p14.CONTRACT.publication.bulk_gis_content_is_noncore,true);assert.equal(p14.CONTRACT.publication.display_only_spatial_disposition_is_not_territorial_authority,true);});
