import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import vm from "node:vm";
import {fileURLToPath} from "node:url";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const text=(p)=>fs.readFileSync(path.join(root,p),"utf8");

test("P2-01 France family remains open after P2-01H direct governance detail decision pending finite whole-family acceptance",()=>{
  const context={window:{}};
  vm.runInNewContext(text("atlas-polity-review-registry.js"),context);
  const reg=context.window.ATLAS_POLITY_REVIEW_REGISTRY;
  assert.equal(reg.schema,"atlas-polity-review-registry/v3");
  const france=reg.historical_family_reviews.find(x=>x.id==="france-regime-family");
  assert.ok(france);
  assert.equal(france.status,"REVIEW_REQUIRED");
  assert.equal(france.terminal_status,null);
  assert.equal(france.suggested_action,"hold");
  assert.match(france.rationale,/P2-01/);
  assert.match(france.rationale,/65/);
  assert.match(france.rationale,/P2-01A/);
  assert.match(france.rationale,/P2-01B/);
  assert.match(france.rationale,/P2-01C/);
  assert.equal(france.left.polity_id,undefined,"do not bind an umbrella family seed to one arbitrary UUID");
  assert.equal(france.right.polity_id,undefined,"do not identify whole regime family with one surviving royal Polity");
  const prior=reg.resolved_history.find(x=>x.id==="france-duplicate-fixed");
  assert.equal(prior.status,"FIXED","old #1357/#1378 closure is preserved as historical proof");
  assert.ok(france.evidence.some(x=>x.includes("#1357")&&x.includes("#1378")));
  const audit=text("docs/POLITY_P2_01_FRANCE_REGIME_FAMILY_AUDIT_20261008.md");
  assert.match(audit,/8 live Polities/);
  assert.match(audit,/65 Authoring/);
  assert.match(audit,/65 Runtime/);
  assert.match(audit,/P2-01A/);
  assert.match(text("docs/ATLAS_CURRENT_WORKSTREAMS.md"),/Immediate bounded next unit: `POLITY-P2-01I`/);
  const correction=text("docs/POLITY_P2_01A_FRANCE_KINGDOM_FIVE_RELINK_20261008.md");
  assert.match(correction,/CORRECTION_APPLIED/);
  assert.match(correction,/65 \/ 0 difference/);
  assert.match(france.rationale,/왕국 5→0/);
  assert.match(france.rationale,/P2-01C/);
  assert.match(france.rationale,/P2-01D/);
  assert.match(france.rationale,/P2-01E/);
  assert.match(france.rationale,/P2-01F/);
  assert.match(france.rationale,/P2-01G/);
  assert.match(france.rationale,/P2-01H/);
  assert.match(france.rationale,/P2-01I/);
  assert.ok(france.evidence.some(x=>x.includes('P2-01H')&&x.includes('NOT_APPLICABLE')));
  const detailContract=text('docs/POLITY_P2_01H_GOVERNANCE_CONTEXT_DETAIL_PROJECTION_20261009.md');
  assert.match(detailContract,/NOT_APPLICABLE/);
  assert.match(detailContract,/POLITY-P2-01I/);
  assert.ok(france.evidence.some(x=>x.includes('P2-01G') && x.includes('AUDIT COMPLETE')));
  const relationAudit=text('docs/POLITY_P2_01G_FRANCE_COUNTRY_UMBRELLA_REPUBLIC_IDENTITY_CONTRACT_20261009.md');
  assert.match(relationAudit,/NO SUPPORTED DIRECT EDGE/);
  assert.match(relationAudit,/65.*Runtime/);
  assert.match(relationAudit,/NO PRODUCTION MUTATION/);
  assert.match(relationAudit,/POLITY-P2-01H/);
  assert.match(france.rationale,/P2-01G/);
  assert.ok(france.evidence.some(x=>x.includes('P2-01F') && x.includes('APPLIED')));
  const vichy=text('docs/POLITY_P2_01F_VICHY_DE_FACTO_GOVERNING_REGIME_20261009.md');
  assert.match(vichy,/SOURCE_BACKED_VICHY_DE_FACTO_GOVERNING_REGIME_APPLIED/);
  assert.match(vichy,/65 Authoring \/65 Runtime \/0/);
  assert.match(vichy,/P2-01G/);
  assert.ok(france.evidence.some(x=>x.includes('P2-01E')&&x.includes('APPLIED')));
  const committee=text('docs/POLITY_P2_01E_VICHY_FREE_FRANCE_AND_COUNTRY_UMBRELLA_20261008.md');
  assert.match(committee,/CORRECTION_APPLIED/);
  assert.match(committee,/65 Authoring \/65 Runtime \/0/);
  assert.match(committee,/P2-01F/);
  assert.ok(france.evidence.some(x=>x.includes('P2-01D')&&x.includes('APPLIED')));
  const govern=text('docs/POLITY_P2_01D_FRANCE_GPRF_FOURTH_GOVERNANCE_20261008.md');
  assert.match(govern,/AUTHENTICATED_CORRECTION_APPLIED/);
  assert.match(govern,/65 Authoring \/ 65 Runtime \/ 0 identity/);
  assert.match(govern,/P2-01E/);
  const war=text("docs/POLITY_P2_01C_FRANCE_WARTIME_REPUBLICAN_CONTINUITY_AUDIT_20261008.md");
  assert.match(war,/65 Authoring \/ 65 matching Runtime \/ 0 mismatches/);
  assert.match(war,/NO PRODUCTION MUTATION/);
  assert.match(war,/P2-01D/);
  assert.match(france.rationale,/P2-01B/);
  assert.ok(france.evidence.some(x=>x.includes("P2-01B")&&x.includes("APPLIED")));
  const third= text("docs/POLITY_P2_01B_FRENCH_THIRD_REPUBLIC_20261008.md");
  assert.match(third,/CORRECTION_APPLIED/);
  assert.match(third,/65 Authoring \/ 65 Runtime \/ 0 drift/);
});